#!/usr/bin/sh
# pdssg - pandoc static site generator
# Makes a static site and Atom feed.

main() {
	echo "### Begin compiling ###"

	# User options
	POSTS_DIR="./archive"
	FEEDS_DIR="./feeds"

	prepare_dst

	NOW_DT="$(date -uIs)"
	MD_FILES=$(find . -regex '.*\.md' | sed '/^\.\/\(_.*\|ast\|pub\|feeds\)/d')
	TMP_DIR="./_tmp"

	cache_posts_metadata $POSTS_DIR
	process_files $MD_FILES
	make_atom_feed $POSTS_DIR
	clearup_files $MD_FILES
	finish

	echo
	echo "### End compiling ###"
	echo
}


# main functions

prepare_dst() {
	echo
	echo "# Preparing ./dst/ directory."
	echo :: $(pwd)

	[ -d ./src/ ] || {
		echo "No  ./src/  directory. Exiting"
		exit
	}

	[ -d ./dst/ ] && {
		echo "Removing previous  ./dst/  build"
		rm -r ./dst/*
	}

	echo "Copying from  ./src/  to  ./dst/"
	cp -r ./src/* ./dst/

	cd ./dst/
	echo :: $(pwd)
}

cache_posts_metadata() {
	echo
	echo "# Caching post metadata."

	posts_dir=$1
	cache_file="$TMP_DIR/$posts_dir/meta.yaml"

	echo -e "New cache file:\t$cache_file"

	mkdir -p $(dirname $cache_file)
	echo "posts:" > $cache_file

	for post in $posts_dir/*
	do
		post_yaml="$(_get_yaml_block $post)"
		filename=$(basename $post)
		slug_attr="slug: ${filename%.md}"
		yaml_block="$(echo -e "$post_yaml\n$slug_attr" | sed 's/^/    /')"

		echo "  -"         >> $cache_file
		echo "$yaml_block" >> $cache_file
	done

	echo "Cache file contents:"
	cat $cache_file
}

process_files() {
	echo
	echo "# Processing Markdown files."

	for md_file in $@
	do
		echo -e "Processing:\t$md_file"

		### prepare flags for pandoc conversion ###
		new_filepath=${md_file%.md}.html

		block="$( _get_yaml_block "$md_file" )"
		bool_toc="$(_get_slug toc "$block")"
		[ -n "$bool_toc" ] && flag_toc="--toc"

		### per file logic ###
		cache_file="$TMP_DIR/${md_file%.md}/meta.yaml"
		[ -f "$cache_file" ] && {
			flag_metadata_file="--metadata-file=$cache_file"
		}

		### create full HTML page ###
		pandoc  \
			-f markdown  -t html  \
			$md_file  -o $new_filepath  \
			-M lang:en  \
			--standalone  \
			--template=./_templates/main.html  \
			-H ./_includes/meta.html  \
			-B ./_includes/header.html  \
			-A ./_includes/footer.html  \
			--email-obfuscation=references  \
			--highlight-style=breezedark  \
			--webtex='https://latex.codecogs.com/svg.latex?'  \
			$flag_toc  \
			$flag_metadata_file  \

		### prepare for next md file
		unset flag_toc
		unset flag_metadata_file
	done
}

make_atom_feed() {
	echo
	echo "# Making atom feed."
	echo "Making base feed document"

	# NOTE: Point of failure. atom_file may not exist. Possible solution is
	# derive posts_dir from existing atom_file's within the tree structure.
	# Then, there would be no need to specify a POSTS_DIR array to pass as an
	# argument to this function, moving configuration to the tree stucture.

	posts_dir="$1"
	cache_file="$TMP_DIR/$posts_dir/meta.yaml"
	atom_file="$FEEDS_DIR/$posts_dir.md"
	atom_out="$FEEDS_DIR/$posts_dir.xml"

	pandoc  \
		-f markdown  -t html  \
		$atom_file  -o $atom_out  \
		--metadata-file=$cache_file  \
		-M "date:$NOW_DT" \
		-M lang:en  \
		--standalone  \
		--template=./_templates/atom.xml

	rm -v $atom_file
	cat $atom_out  > ./_tmp/atom.xml

	echo "Inserting contents"

	posts_reverse=$(echo $posts_dir/*.html | sed 's/ /\n/g' | sort -r)
	for post in $posts_reverse
	do
		echo -e "Inserting:\t$post"

		sed -n '/<!--CONTENT-->/,$!p' $TMP_DIR/atom.xml    > $TMP_DIR/before.xml
		cat "$post" | sed -n '/<article>/,/<\/article>/p'  > $TMP_DIR/content.xml
		sed -n '1,/<!--CONTENT-->/!p' $TMP_DIR/atom.xml    > $TMP_DIR/after.xml
		cat $TMP_DIR/{before,content,after}.xml            > $TMP_DIR/atom.xml
	done

	echo "Finishing feed"
	cat $TMP_DIR/atom.xml  > $atom_out
}

clearup_files() {
	echo
	echo "# Clearing up Markdown files."

	rm -v $@
	rm -rv $( find . -path './_*' -type d )
}

finish() {
	echo
	echo "# Finished compiling."

	cd ..
	echo :: $(pwd)
	echo "Finished"
}


# util functions

_get_yaml_block() {
	md_file="$1"
	block="$(sed -n -e '1,/---/p' $md_file | grep -v '\-\-\-')"
	echo "$block"
}

_get_slug() {
	key="$1"
	block="$2"

	line=$(echo "$block" | grep "^$key\s*:\s*")
	title=$(echo $line | sed -e "s/^$key\s*:\s*//")
	slug=$(echo $title | sed -e 's/\s*$//' -e 's/\s\+/-/g')
	neatslug=$(
		echo $slug  \
		| tr '[:upper:]' '[:lower:]'  \
		| tr -cd "[:alpha:][:digit:]-"
	)
	echo $neatslug
}


# main

main

